"""fix cascade deleting in m2m relationship

Revision ID: 140faf4b832e
Revises: a3c452eab74c
Create Date: 2024-09-15 18:36:35.749341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140faf4b832e'
down_revision: Union[str, None] = 'a3c452eab74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genre_association_artist_id_fkey', 'artist_genre_association', type_='foreignkey')
    op.drop_constraint('artist_genre_association_genre_id_fkey', 'artist_genre_association', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genre_association', 'genre', ['genre_id'], ['name'])
    op.create_foreign_key(None, 'artist_genre_association', 'artist', ['artist_id'], ['artist_id'])
    op.drop_constraint('artist_track_association_track_id_fkey', 'artist_track_association', type_='foreignkey')
    op.drop_constraint('artist_track_association_artist_id_fkey', 'artist_track_association', type_='foreignkey')
    op.create_foreign_key(None, 'artist_track_association', 'artist', ['artist_id'], ['artist_id'])
    op.create_foreign_key(None, 'artist_track_association', 'track', ['track_id'], ['track_id'])
    op.drop_constraint('playlist_track_association_track_id_fkey', 'playlist_track_association', type_='foreignkey')
    op.drop_constraint('playlist_track_association_playlist_version_id_fkey', 'playlist_track_association', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_track_association', 'track', ['track_id'], ['track_id'])
    op.create_foreign_key(None, 'playlist_track_association', 'playlist_version', ['playlist_version_id'], ['version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_track_association', type_='foreignkey')
    op.drop_constraint(None, 'playlist_track_association', type_='foreignkey')
    op.create_foreign_key('playlist_track_association_playlist_version_id_fkey', 'playlist_track_association', 'playlist_version', ['playlist_version_id'], ['version_id'], ondelete='CASCADE')
    op.create_foreign_key('playlist_track_association_track_id_fkey', 'playlist_track_association', 'track', ['track_id'], ['track_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'artist_track_association', type_='foreignkey')
    op.drop_constraint(None, 'artist_track_association', type_='foreignkey')
    op.create_foreign_key('artist_track_association_artist_id_fkey', 'artist_track_association', 'artist', ['artist_id'], ['artist_id'], ondelete='CASCADE')
    op.create_foreign_key('artist_track_association_track_id_fkey', 'artist_track_association', 'track', ['track_id'], ['track_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'artist_genre_association', type_='foreignkey')
    op.drop_constraint(None, 'artist_genre_association', type_='foreignkey')
    op.create_foreign_key('artist_genre_association_genre_id_fkey', 'artist_genre_association', 'genre', ['genre_id'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('artist_genre_association_artist_id_fkey', 'artist_genre_association', 'artist', ['artist_id'], ['artist_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
