"""Fix analysis-playlist o2o relationship

Revision ID: 836fea1556bd
Revises: 3f6d6a6f1659
Create Date: 2024-09-18 16:23:31.131982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836fea1556bd'
down_revision: Union[str, None] = '3f6d6a6f1659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'analysis', ['playlist_version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='unique')
    op.alter_column('analysis', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
