"""Add names for playlist_version forgein keys

Revision ID: f552e941d282
Revises: d2adfd6bb3c5
Create Date: 2024-09-17 17:34:36.069049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f552e941d282'
down_revision: Union[str, None] = 'd2adfd6bb3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_track_association_playlist_version_id_fkey', 'playlist_track_association', type_='foreignkey')
    op.drop_constraint('playlist_track_association_track_id_fkey', 'playlist_track_association', type_='foreignkey')
    op.create_foreign_key('track_id_playlist', 'playlist_track_association', 'track', ['track_id'], ['track_id'], ondelete='CASCADE')
    op.create_foreign_key('playlist_version_id', 'playlist_track_association', 'playlist_version', ['playlist_version_id'], ['version_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('playlist_version_id', 'playlist_track_association', type_='foreignkey')
    op.drop_constraint('track_id_playlist', 'playlist_track_association', type_='foreignkey')
    op.create_foreign_key('playlist_track_association_track_id_fkey', 'playlist_track_association', 'track', ['track_id'], ['track_id'])
    op.create_foreign_key('playlist_track_association_playlist_version_id_fkey', 'playlist_track_association', 'playlist_version', ['playlist_version_id'], ['version_id'])
    # ### end Alembic commands ###
