"""Made genre as enum instead of table

Revision ID: f9d6a96241fe
Revises: 140faf4b832e
Create Date: 2024-09-15 18:43:55.861118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d6a96241fe'
down_revision: Union[str, None] = '140faf4b832e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_genre_association')
    op.drop_table('genre')

    genre_enum = sa.Enum(
        'UNKNOWN', 'ACOUSTIC', 'AFROBEAT', 'ALT_ROCK', 'ALTERNATIVE', 'AMBIENT',
        'ANIME', 'BLACK_METAL', 'BLUEGRASS', 'BLUES', 'BOSSANOVA', 'BRAZIL',
        'BREAKBEAT', 'BRITISH', 'CANTOPOP', 'CHICAGO_HOUSE', 'CHILDREN', 'CHILL',
        'CLASSICAL', 'CLUB', 'COMEDY', 'COUNTRY', 'DANCE', 'DANCEHALL', 'DEATH_METAL',
        'DEEP_HOUSE', 'DETROIT_TECHNO', 'DISCO', 'DISNEY', 'DRUM_AND_BASS', 'DUB',
        'DUBSTEP', 'EDM', 'ELECTRO', 'ELECTRONIC', 'EMO', 'FOLK', 'FORRO', 'FRENCH',
        'FUNK', 'GARAGE', 'GERMAN', 'GOSPEL', 'GOTH', 'GRINDCORE', 'GROOVE', 'GRUNGE',
        'GUITAR', 'HAPPY', 'HARD_ROCK', 'HARDCORE', 'HARDSTYLE', 'HEAVY_METAL', 'HIP_HOP',
        'HOLIDAYS', 'HONKY_TONK', 'HOUSE', 'IDM', 'INDIAN', 'INDIE', 'INDIE_POP',
        'INDUSTRIAL', 'IRANIAN', 'J_DANCE', 'J_IDOL', 'J_POP', 'J_ROCK', 'JAZZ',
        'K_POP', 'KIDS', 'LATIN', 'LATINO', 'MALAY', 'MANDOPOP', 'METAL', 'METAL_MISC',
        'METALCORE', 'MINIMAL_TECHNO', 'MOVIES', 'MPB', 'NEW_AGE', 'NEW_RELEASE',
        'OPERA', 'PAGODE', 'PARTY', 'PHILIPPINES_OPM', 'PIANO', 'POP', 'POP_FILM',
        'POST_DUBSTEP', 'POWER_POP', 'PROGRESSIVE_HOUSE', 'PSYCH_ROCK', 'PUNK', 'PUNK_ROCK',
        'R_N_B', 'RAINY_DAY', 'REGGAE', 'REGGAETON', 'ROAD_TRIP', 'ROCK', 'ROCK_N_ROLL',
        'ROCKABILLY', 'ROMANCE', 'SAD', 'SALSA', 'SAMBA', 'SERTANEJO', 'SHOW_TUNES',
        'SINGER_SONGWRITER', 'SKA', 'SLEEP', 'SONGWRITER', 'SOUL', 'SOUNDTRACKS', 'SPANISH',
        'STUDY', 'SUMMER', 'SWEDISH', 'SYNTH_POP', 'TANGO', 'TECHNO', 'TRANCE', 'TRIP_HOP',
        'TURKISH', 'WORK_OUT', 'WORLD_MUSIC',
        name='genre'
    )
    genre_enum.create(op.get_bind())
    op.add_column('artist', sa.Column('genres', postgresql.ARRAY(genre_enum), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.create_table('genre',
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('name', name='genre_pkey'),
                    sa.UniqueConstraint('name', name='genre_name_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('artist_genre_association',
                    sa.Column('artist_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('genre_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'],
                                            name='artist_genre_association_artist_id_fkey'),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.name'], name='artist_genre_association_genre_id_fkey')
                    )
    # ### end Alembic commands ###
