"""Fix cascade deleting

Revision ID: fe2363048054
Revises: f011d768fbc4
Create Date: 2024-09-17 17:26:19.484460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2363048054'
down_revision: Union[str, None] = 'f011d768fbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_track_association_track_id_fkey', 'artist_track_association', type_='foreignkey')
    op.drop_constraint('artist_track_association_artist_id_fkey', 'artist_track_association', type_='foreignkey')
    op.create_foreign_key(None, 'artist_track_association', 'artist', ['artist_id'], ['artist_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artist_track_association', 'track', ['track_id'], ['track_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_track_association', type_='foreignkey')
    op.drop_constraint(None, 'artist_track_association', type_='foreignkey')
    op.create_foreign_key('artist_track_association_artist_id_fkey', 'artist_track_association', 'artist', ['artist_id'], ['artist_id'])
    op.create_foreign_key('artist_track_association_track_id_fkey', 'artist_track_association', 'track', ['track_id'], ['track_id'])
    # ### end Alembic commands ###
